version: "2.2"
services:
    mysql:
        image: mysql/mysql-server:5.7
        restart: always
        container_name: my_mysql
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'pass'
    netapi:
        build: .
        restart: always
        container_name: my_dotnet_api
        ports:
          - '80:80'
        links:
          - mysql:db
    swagger:
        image: swaggerapi/swagger-ui
        restart: always
        container_name: my_swagger
        ports:
          - '4444:8080'
        environment:
          - URL=netapi/swagger/v1/swagger.json
    seq:
        image: datalust/seq
        restart: always
        container_name: my_seq
        ports:
          - '3333:80'
        environment: 
          - ACCEPT_EULA=Y