version: "2.2"
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: my_mysql
    environment:
      MYSQL_ROOT_HOST: 172.16.238.10 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - buzzer
  netapi:
    build: .
    container_name: my_dotnet_api
    ports:
      - '80:80'
    environment:
      SEQ_URL: 'http://172.16.238.9:5341'
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql:db
    networks:
      buzzer:
        ipv4_address: 172.16.238.10 
  swagger:
    image: swaggerapi/swagger-ui
    container_name: my_swagger
    ports:
      - '4444:8080'
    links:
      - netapi:api
    environment:
      - URL=http://buzzer1.westeurope.cloudapp.azure.com/swagger/v1/swagger.json
    networks:
      - buzzer
  seq:
    image: datalust/seq
    container_name: my_seq
    ports:
      - '3333:80'
    environment: 
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      buzzer:
        ipv4_address: 172.16.238.9 
volumes: 
  db-data:
  seq-data:
networks:
  buzzer:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1