version: "2.2"
services:
    mysql:
        image: mysql/mysql-server:5.7
        container_name: my_mysql
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'pass'
        ports:
          - '5959:3306'
    netapi:
        build: .
        restart: always
        container_name: my_dotnet_api
        ports:
          - '80:80'
        links:
          - mysql:db
        environment:
          - DATABASE_URL=db