// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buzzerApi.Models;

namespace buzzerApi.Migrations
{
    [DbContext(typeof(BuzzerApiContext))]
    [Migration("20191110175020_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("buzzerApi.Models.QuestionTexte", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("Proposition1")
                        .IsRequired();

                    b.Property<string>("Proposition2")
                        .IsRequired();

                    b.Property<string>("Proposition3")
                        .IsRequired();

                    b.Property<string>("Proposition4")
                        .IsRequired();

                    b.Property<string>("Question")
                        .IsRequired();

                    b.Property<string>("Reponse")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("QuestionTexte");
                });

            modelBuilder.Entity("buzzerApi.Models.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
