// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buzzerApi.Models;

namespace buzzerApi.Migrations
{
    [DbContext(typeof(BuzzerApiContext))]
    [Migration("20191014074618_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("buzzerApi.Models.QuestionTexte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("proposition1")
                        .IsRequired();

                    b.Property<string>("proposition2")
                        .IsRequired();

                    b.Property<string>("proposition3")
                        .IsRequired();

                    b.Property<string>("proposition4")
                        .IsRequired();

                    b.Property<string>("question")
                        .IsRequired();

                    b.Property<string>("reponse")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("QuestionTexte");
                });
#pragma warning restore 612, 618
        }
    }
}
